"""Achievement (Trophy Room) definitions. Each has a check(stats) -> bool,
where stats is the dict built by app.py's build_stats_snapshot()."""

def achievement_definitions():
    return [
        dict(key="first_quiz", name="First Steps", emoji="🌱", rarity="common",
             desc="Complete your first quiz.", check=lambda s: s["quizzes_completed"] >= 1),
        dict(key="level_5", name="Rising Star", emoji="⭐", rarity="common",
             desc="Reach Level 5.", check=lambda s: s["level"] >= 5),
        dict(key="level_10", name="Dedicated Student", emoji="🎓", rarity="uncommon",
             desc="Reach Level 10.", check=lambda s: s["level"] >= 10),
        dict(key="level_20", name="Fluent Explorer", emoji="🧭", rarity="rare",
             desc="Reach Level 20.", check=lambda s: s["level"] >= 20),
        dict(key="level_50", name="Sprachmeister", emoji="👑", rarity="legendary",
             desc="Reach the maximum Level 50.", check=lambda s: s["level"] >= 50),
        dict(key="streak_7", name="One Week Strong", emoji="🔥", rarity="uncommon",
             desc="Reach a 7-day streak.", check=lambda s: s["current_streak"] >= 7),
        dict(key="streak_30", name="Unbreakable", emoji="💪", rarity="rare",
             desc="Reach a 30-day streak.", check=lambda s: s["current_streak"] >= 30),
        dict(key="streak_100", name="Legend Status", emoji="🏆", rarity="legendary",
             desc="Reach a 100-day streak.", check=lambda s: s["current_streak"] >= 100),
        dict(key="words_25", name="Word Collector", emoji="📖", rarity="common",
             desc="Save 25 words.", check=lambda s: s["words_saved"] >= 25),
        dict(key="words_100", name="Vocabulary Vault", emoji="📚", rarity="rare",
             desc="Save 100 words.", check=lambda s: s["words_saved"] >= 100),
        dict(key="words_mastered_25", name="Mastery Begins", emoji="🧠", rarity="uncommon",
             desc="Master 25 flashcards.", check=lambda s: s["words_mastered"] >= 25),
        dict(key="perfect_quiz", name="Perfectionist", emoji="💯", rarity="uncommon",
             desc="Score 100% on a quiz.", check=lambda s: s["perfect_quizzes"] >= 1),
        dict(key="perfect_quiz_10", name="Flawless", emoji="✨", rarity="rare",
             desc="Score 100% on 10 quizzes.", check=lambda s: s["perfect_quizzes"] >= 10),
        dict(key="stories_5", name="Bookworm", emoji="🐛", rarity="common",
             desc="Finish 5 stories.", check=lambda s: s["stories_completed"] >= 5),
        dict(key="stories_all", name="Master Reader", emoji="📕", rarity="legendary",
             desc="Finish every available story.", check=lambda s: s["stories_completed"] >= s["stories_total"]),
        dict(key="coins_1000", name="Coin Collector", emoji="💰", rarity="uncommon",
             desc="Accumulate 1000 coins at once.", check=lambda s: s["coins"] >= 1000),
        dict(key="chests_10", name="Treasure Hunter", emoji="📦", rarity="uncommon",
             desc="Open 10 loot chests.", check=lambda s: s["chests_opened"] >= 10),
        dict(key="legendary_item", name="Legendary Find", emoji="🌟", rarity="legendary",
             desc="Own a legendary item.", check=lambda s: s["legendary_items_owned"] >= 1),
        dict(key="pet_owner", name="New Best Friend", emoji="🐾", rarity="common",
             desc="Adopt your first pet.", check=lambda s: s["pets_owned"] >= 1),
        dict(key="quizzes_50", name="Quiz Machine", emoji="⚙️", rarity="rare",
             desc="Complete 50 quizzes.", check=lambda s: s["quizzes_completed"] >= 50),
    ]
